### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by ianmiell** [ianmiell/shutit-openshift-cluster#8]
```
ompiling Cookbooks...ESC[0m

ESC[0m

================================================================================ESC[0m

ESC[31mRecipe Compile Error in /var/chef/cache/cookbooks/cookbook-openshift3/recipes/default.rbESC[0m

================================================================================ESC[0m



ESC[0mTypeErrorESC[0m

---------ESC[0m

no implicit conversion of String into IntegerESC[0m



ESC[0mCookbook Trace:ESC[0m

---------------ESC[0m

  /var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:71:in `[]'

ESC[0m  /var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:71:in `on_certificate_server?'

ESC[0m  /var/chef/cache/cookbooks/cookbook-openshift3/recipes/validate.rb:14:in `from_file'

ESC[0m  /var/chef/cache/cookbooks/cookbook-openshift3/recipes/default.rb:23:in `from_file'ESC[0m



ESC[0mRelevant File Content:ESC[0m

----------------------ESC[0m

/var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:

ESC[0m

ESC[0m 64:      end

ESC[0m 65:  

ESC[0m 66:      def on_first_etcd?

ESC[0m 67:        first_etcd['fqdn'] == node['fqdn']

ESC[0m 68:      end

ESC[0m 69:  

ESC[0m 70:      def on_certificate_server?

ESC[0m 71>>       certificate_server['fqdn'] == node['fqdn']

ESC[0m 72:      end

ESC[0m 73:  

ESC[0m 74:      def on_control_plane_server?

ESC[0m 75:        on_certificate_server? || on_etcd_server? || on_master_server?

ESC[0m 76:      end

ESC[0m 77:  

ESC[0m 78:      def remove_dir(path)

ESC[0m 79:        FileUtils.rm_rf(Dir.glob(path))

ESC[0m 80:      end

ESC[0m

ESC[0mSystem Info:ESC[0m

------------ESC[0m

chef_version=13.5.3

ESC[0mplatform=centos

```

**Comment by ianmiell** [comment]
```
TypeError
---------
no implicit conversion of String into Integer

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:71:in `[]'
  /var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:71:in `on_certificate_server?'
  /var/chef/cache/cookbooks/cookbook-openshift3/recipes/validate.rb:14:in `from_file'
  /var/chef/cache/cookbooks/cookbook-openshift3/recipes/default.rb:23:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:

 64:      end
 65:  
 66:      def on_first_etcd?
 67:        first_etcd['fqdn'] == node['fqdn']
 68:      end
 69:  
 70:      def on_certificate_server?
 71>>       certificate_server['fqdn'] == node['fqdn']
 72:      end
 73:  
 74:      def on_control_plane_server?
 75:        on_certificate_server? || on_etcd_server? || on_master_server?
 76:      end
 77:  
 78:      def remove_dir(path)
 79:        FileUtils.rm_rf(Dir.glob(path))
 80:      end

System Info:
------------
chef_version=13.5.3
platform=centos
platform_version=7.4.1708
ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
program_name=chef-client worker: ppid=18029;start=19:00:03;
executable=/opt/chef/bin/chef-client

```

**Comment by ianmiell** [comment]
@IshentRas did something change with the certificate_server logic?

```
[root@chefwkstn ~]# knife node show master1.vagrant.test
Node Name:   master1.vagrant.test
Environment: _default
FQDN:        master1.vagrant.test
IP:          172.28.128.3
Run List:    role[role], role[testcluster1_use_role_based_duty_discovery], role[testcluster1_openshift_master_duty], role[testcluster1_openshift_first_master_duty], role[testcluster1_openshift_etcd_duty], role[testcluster1_openshift_first_etcd_duty]
Roles:       
Recipes:     
Platform:    centos 7.4.1708
Tags:        
```

**Comment by ianmiell** [comment]
Basic test works, so must be upgrade-related.

**Comment by IshentRas** [comment]
Not sure if it was related but thanks anyway :+1: 
I have just pushed a new logic: https://github.com/IshentRas/cookbook-openshift3/commit/787b8cfc0d6edb4d4e7d409eaf37c0eb0f5bd6d3

**Comment by ianmiell** [comment]
Still happening:

```
/usr/bin/python /usr/local/bin/shutit build -l debug -d bash --echo --interactive 0 -m shutit-library/vagrant:shutit-library/virtualbox -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster test_config_dir test_multi_node_separate_etcd -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster ose_version 1.3.3-1.el7 -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster ose_major_version 1.3 -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster cookbook_branch master -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_yum_cookbook_version latest -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_iptables_cookbook_version latest -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_selinux_policy_cookbook_version latest -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_compat_resource_cookbook_version latest -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster inject_compat_resource false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_deploy_method server -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_deploy_containerized false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_13_14 false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_14_15 false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_15_36 false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_36_37 false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster openshift_docker_image_version v1.3.3 --nocolor -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_13_14 true -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_14_15 true -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_15_36 true -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_36_37 true --interactive 0
```

Think it might be 1.3
